### ISSUE TITLE
Deta deployment not working

### ISSUE THREAD

**Issue by sany2k8** [kingabzpro/FastAPI-ML-Project#1]
While trying to deploy on deta its not working, throws these error msg,

```
Traceback (most recent call last):
  File "/opt/python/detalib/debugger.py", line 142, in wrap
    result = func(event, context)
  File "/var/task/_entry.py", line 12, in handler
    import main  # noqa
  File "/var/task/main.py", line 2, in <module>
    from ml import nlp
  File "/var/task/ml.py", line 1, in <module>
    import spacy
  File "/opt/python/spacy/__init__.py", line 15, in <module>
    from .cli.info import info  # noqa: F401
  File "/opt/python/spacy/cli/__init__.py", line 3, in <module>
    from ._util import app, setup_cli  # noqa: F401
  File "/opt/python/spacy/cli/_util.py", line 8, in <module>
    import typer
  File "/opt/python/typer/__init__.py", line 29, in <module>
    from .main import Typer as Typer
  File "/opt/python/typer/main.py", line 11, in <module>
    from .completion import get_completion_inspect_parameters
  File "/opt/python/typer/completion.py", line 10, in <module>
    import click._bashcomplete
ModuleNotFoundError: No module named 'click._bashcomplete'
```

**Comment by kingabzpro** [comment]
In my end it is not reproduceable. Can you describe more about how are you deploying it? 
![image](https://user-images.githubusercontent.com/36753484/132957368-df5ad97d-0706-446e-80dd-0d4eaa577770.png)

Have you tried clicking on the button?
[![Deploy](https://button.deta.dev/1/svg)](https://go.deta.dev/deploy)
